# Makefile.deps created Thu May 15 21:08:17 PDT 2014
debug.o: debug.c debug.h
hashset.o: hashset.c debug.h hashset.h strhash.h
strhash.o: strhash.c strhash.h
spellchk.o: spellchk.c debug.h hashset.h yyextern.h
