#!/bin/bash
# $Id: mkjbox,v 1.12 2014-02-13 18:36:39-08 - - $

function catnv() {
   for arg in $*
   do
      if [ "$arg" = "-f" ]
      then
         echo -e '\f'
      else
         echo ::::::::::::::::::::::::::::::::
         echo $arg
         echo ::::::::::::::::::::::::::::::::
         cat -nv $arg
      fi
   done
}

cid + $0 jbox.java
javac jbox.java
echo Main-class: jbox_main >Manifest
classes='jbox.class jbox_code.class jbox_main.class'
jar cfm jbox.jar Manifest $classes
chmod +x jbox.jar
./jbox.jar >jbox.output 2>&1

catnv jbox.java -f Manifest jbox.output mkjbox >jbox.lis
mkpspdf Listing.jbox.ps jbox.lis
rm Manifest jbox.jar *.class jbox.output jbox.lis

